# Change these first
owner: auroraanna # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: aaura-w3-strawb
    url: https://annaaurora.eu
    ipv6: true
  - name: aaura-w3-strawb Atom feed
    url: https://annaaurora.eu/atom.xml
    ipv6: true
  - name: meme-bingo-web
    url: https://bingo.annaaurora.eu
    ipv6: true
  - name: kaufkauflist
    url: https://kaufkauflist.annaaurora.eu
    ipv6: true
  - name: WKD
    url: https://openpgpkey.annaaurora.eu/.well-known/openpgpkey/annaaurora.eu/hu/fxy63pyohfbm34b533z1nk4bhfhbkpsh
    ipv6: true
  - name: Find Billy!
    url: https://find-billy.annaaurora.eu
    ipv6: true
  - name: ntfy
    url: https://ntfy.annaaurora.eu
    ipv6: true
  - name: matrix (server)
    url: "https://matrix.annaaurora.eu:443/_conduwuit/server_version"
    ipv6: true
  - name: peertube
    url: "https://röhre.annaaurora.eu"
    ipv6: true
  - name: nyancat telnet
    check: "tcp-ping"
    url: annaaurora.eu
    port: 23
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.annaaurora.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status monitor for annaaurora.eu"
  introMessage: "This is a status monitor for services hosted on annaaurora.eu and subdomains, hosted on GitHub, not on the same server as the services it's monitoring so that it doesn't go down with them."
  navbar:
    - title: annaaurora.eu
      href: https://annaaurora.eu
    - title: GitHub repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
